//@version=6
indicator("Persistent declarations demo")

//@variable A *persistent* variable. The script initializes this variable only on the *first execution*. 
//          The variable preserves all changes to its value on each closed bar. 
var int x = 0

// Increase the value of `x` by 10 on every bar.
x += 10

// Plot the `x` series on the chart. 
// Because the script declares `x` using `var` and then increments its value, the value never resets to 0.
// The plotted value is 10 on the first bar, 20 on the next, and so on. 
plot(x, "`x` series", color.blue, 3)
