//@version=6
indicator("Repeated declarations demo")

//@variable A user-defined variable. The script declares this variable and initializes it to 0 on *every* execution.
int x = 0

// Increase the value of `x` by 10 on every bar.
x += 10

// Plot the value of `x`.
// Because `x` begins at 0 on every execution, and the script adds 10 to that value, the plotted value is always 10.
plot(x, "`x` value", color.blue, 3)
